import { PlanEntitlementsSchema, type PlanEntitlements, PlanTier } from './plan';

export const BUILT_IN_PLANS = {
  [PlanTier.LOCAL]: PlanEntitlementsSchema.parse({
    maxProjects: 1,
    maxUsersPerProject: 0,
    backupEnabled: false,
    backupStorageBytes: 0,
    manualBackupEnabled: false,
    customModulesEnabled: false,
    auditRetentionDays: 0,
    multiAdminAllowed: false,
    maxDevicesPerUser: 1,
  }),
  [PlanTier.STARTER]: PlanEntitlementsSchema.parse({
    maxProjects: 1,
    maxUsersPerProject: 3,
    backupEnabled: true,
    backupScheduleCron: '0 2 * * *',
    backupStorageBytes: 50 * 1024 * 1024 * 1024,
    manualBackupEnabled: false,
    customModulesEnabled: false,
    auditRetentionDays: 365,
    multiAdminAllowed: false,
    maxDevicesPerUser: 2,
  }),
  [PlanTier.TEAM]: PlanEntitlementsSchema.parse({
    maxProjects: 1,
    maxUsersPerProject: 10,
    backupEnabled: true,
    backupScheduleCron: '0 2 * * *',
    backupStorageBytes: 500 * 1024 * 1024 * 1024,
    manualBackupEnabled: false,
    customModulesEnabled: false,
    auditRetentionDays: 1825,
    multiAdminAllowed: false,
    maxDevicesPerUser: 2,
  }),
  [PlanTier.ENTERPRISE]: PlanEntitlementsSchema.parse({
    maxProjects: 100,
    maxUsersPerProject: 1000,
    backupEnabled: true,
    backupScheduleCron: '0 2 * * *',
    backupStorageBytes: 5 * 1024 * 1024 * 1024 * 1024,
    manualBackupEnabled: true,
    customModulesEnabled: true,
    auditRetentionDays: -1,
    multiAdminAllowed: false,
    maxDevicesPerUser: 2,
  }),
} as const satisfies Record<PlanTier, PlanEntitlements>;
